### ISSUE TITLE
두번째 주차 문제

### ISSUE THREAD

**Issue by CokeLee777** [JSY8869/CodingTestStudy#4]
1. Greedy
2. DFS/BFS
3. Binary Search
4. Dynamic Programming

**Comment by JSY8869** [comment]
1. [55. Jump Game](https://leetcode.com/problems/jump-game/)
2. [207. Course Schedule](https://leetcode.com/problems/course-schedule/)
3. [287. Find the Duplicate Number](https://leetcode.com/problems/find-the-duplicate-number/)
4. [131. Palindrome Partitioning](https://leetcode.com/problems/palindrome-partitioning/)
