### ISSUE TITLE
세번째 주차 문제

### ISSUE THREAD

**Issue by CokeLee777** [JSY8869/CodingTestStudy#7]
1. Greedy
2. DFS/BFS
3. Divide and Conquer
4. Backtracking

**Comment by JSY8869** [comment]
1. [525. Contiguous Array](https://leetcode.com/problems/contiguous-array/)
2. [547. Number of Provinces](https://leetcode.com/problems/number-of-provinces/)
3. [395. Longest Substring with At Least K Repeating Characters](https://leetcode.com/problems/longest-substring-with-at-least-k-repeating-characters/)
4. [51. N-Queens](https://leetcode.com/problems/n-queens/)
